CREATE TABLE STUDENT_MASTER (
	student_code number(6) NOT NULL,
	student_name varchar2(50) NOT NULL,
	dept_code number(2),
	student_dob date,
	student_address varchar2(240)
);

INSERT INTO STUDENT_MASTER
	VALUES(7866, 'ARNAV SHARMA', 82, TO_DATE('15-01-1996','DD-MM-YYYY'), 'MODEL TOWN DELHI');
INSERT INTO STUDENT_MASTER
	VALUES(7868, 'ARUSHI', 81, TO_DATE('07-04-1996','DD-MM-YYYY'), 'PITAMPURA DELHI');
INSERT INTO STUDENT_MASTER
	VALUES(7598, 'AKSHITA SACHDEVA', 84, TO_DATE('23-09-1996','DD-MM-YYYY'), 'YAMUNANAGAR HARYANA');
INSERT INTO STUDENT_MASTER
	VALUES(7896, 'RUSHALI TICKOO', 86, TO_DATE('12-05-1990','DD-MM-YYYY'), 'BANGALORE');
INSERT INTO STUDENT_MASTER
	VALUES(7980, 'APRAJITA CHAUHAN', 81, TO_DATE('21-02-1996','DD-MM-YYYY'), 'SHALIMAR BAGH DELHI');
COMMIT;